---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rapidask
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rapidask-role
  namespace: default
rules:
  - apiGroups:
      - "apps"
    resources:
      - replicasets
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - watch
      - list
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rapidask-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: rapidask
    namespace: default
roleRef:
  kind: Role
  name: rapidask-role
  apiGroup: rbac.authorization.k8s.io
