apiVersion: v1
kind: Service
metadata:
  name: rapidask-scheduler-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: rapidask-scheduler
  ports:
    - protocol: TCP
      port: 8786
      targetPort: 8786
      nodePort: 30000